name: Run tests
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: print working directory
        run: pwd
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install pytest
        run: |
          python -m pip install --upgrade pytest
      - name: Run tests on pytest
        run: |
          python3 -m pytest